//! Trigger `grub-mkconfig` to regenerate `/boot/grub/grub.cfg`.
//!
//! After [`crate::grub_manager::set_grub_value`] atomically writes
//! `/etc/default/grub`, the changes are on-disk but not yet active at boot.
//! GRUB reads `/boot/grub/grub.cfg`, which is only regenerated by an explicit
//! `grub-mkconfig -o /boot/grub/grub.cfg` (Debian/Ubuntu/Arch) or
//! `grub2-mkconfig -o /boot/grub/grub.cfg` (RHEL/Fedora/openSUSE) invocation.
//!
//! This module locates whichever variant is present on `$PATH` and runs it.
//!
//! # Error mapping
//!
//! All errors are surfaced as [`BootControlError::EspScanFailed`] with a
//! human-readable reason string. Clients catch
//! `org.bootcontrol.Error.EspScanFailed` over D-Bus.

use std::path::Path;

use bootcontrol_core::error::BootControlError;
use tracing::info;
use which::which;

/// Locate and run `grub-mkconfig` (or `grub2-mkconfig`) to regenerate the
/// GRUB configuration file.
///
/// The function probes `$PATH` for `grub-mkconfig` first and falls back to
/// `grub2-mkconfig` so that both Debian/Ubuntu/Arch and RHEL/Fedora families
/// are supported transparently.
///
/// # Arguments
///
/// * `output_path` — Destination path for the generated `grub.cfg`.
///   Production code passes `/boot/grub/grub.cfg`; tests inject a temporary
///   path to avoid touching the live system.
///
/// # Errors
///
/// Returns [`BootControlError::EspScanFailed`] when:
/// - Neither `grub-mkconfig` nor `grub2-mkconfig` is found on `$PATH`.
/// - The command exits with a non-zero status (the reason includes stderr).
/// - Any I/O error occurs while spawning the child process.
///
/// # Examples
///
/// ```no_run
/// use std::path::Path;
/// use bootcontrold::grub_rebuild::run_grub_mkconfig;
///
/// // Production usage — requires root and a real GRUB installation.
/// run_grub_mkconfig(Path::new("/boot/grub/grub.cfg")).unwrap();
/// ```
pub fn run_grub_mkconfig(output_path: &Path) -> Result<(), BootControlError> {
    // ── Step 1: Locate the binary ─────────────────────────────────────────────
    let binary = which("grub-mkconfig")
        .or_else(|_| which("grub2-mkconfig"))
        .map_err(|_| BootControlError::EspScanFailed {
            reason: "grub-mkconfig not found; install grub-common or grub2-common".to_string(),
        })?;

    info!(binary = ?binary, output_path = ?output_path, "running grub-mkconfig");

    // ── Step 2: Run the command, capturing stdout + stderr ────────────────────
    let output = std::process::Command::new(&binary)
        .arg("-o")
        .arg(output_path)
        .output()
        .map_err(|e| BootControlError::EspScanFailed {
            reason: format!("failed to spawn {}: {e}", binary.display()),
        })?;

    // ── Step 3: Check exit status ─────────────────────────────────────────────
    if !output.status.success() {
        let code = output
            .status
            .code()
            .map(|c| c.to_string())
            .unwrap_or_else(|| "signal".to_string());
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(BootControlError::EspScanFailed {
            reason: format!("grub-mkconfig failed (exit {code}): {stderr}"),
        });
    }

    info!(output_path = ?output_path, "grub-mkconfig completed successfully");
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::{Mutex, MutexGuard};
    use tempfile::{NamedTempFile, TempDir, TempPath};

    // ── PATH serialization lock ───────────────────────────────────────────────
    //
    // Tests that manipulate the process-wide PATH environment variable MUST
    // hold this lock for the duration of the manipulation. Because Rust tests
    // run in parallel by default and PATH is a global resource, concurrent
    // manipulation would cause non-deterministic failures.
    //
    // Acquire it via [`lock_path`] (below), which recovers from poisoning so
    // that a panic in one test does not cascade-fail every other test that
    // touches PATH.
    pub(crate) static PATH_LOCK: Mutex<()> = Mutex::new(());

    /// Acquire [`PATH_LOCK`], tolerating a previously-poisoned lock.
    ///
    /// `Mutex::lock` returns `Err(PoisonError)` if a thread previously panicked
    /// while holding the lock. The PATH guard itself is just `()` — there is
    /// no inner state to corrupt — so recovery via `into_inner` is safe and
    /// prevents one flaky test from cascading into spurious failures across
    /// the rest of the file.
    pub(crate) fn lock_path() -> MutexGuard<'static, ()> {
        PATH_LOCK.lock().unwrap_or_else(|e| e.into_inner())
    }

    // ── Helper: create a temporary shell script ───────────────────────────────

    /// Write a shell script to a `NamedTempFile`, set it executable, then close
    /// the write fd and return the resulting [`TempPath`] plus the owning
    /// [`TempDir`] (kept alive so the directory is not deleted while the file
    /// is in use).
    ///
    /// Closing the write fd before any caller execs the script is essential on
    /// kernels that enforce `ETXTBSY`: spawning a binary whose file is still
    /// open for writing yields `Text file busy` and panics the test. This
    /// surfaces reliably on aarch64 / QEMU and was the root cause of the
    /// poisoned-`PATH_LOCK` cascade observed under those configurations.
    fn make_script(body: &str) -> (TempPath, TempDir) {
        let dir = TempDir::new().expect("tempdir");
        let mut script = NamedTempFile::new_in(dir.path()).expect("script tempfile");
        writeln!(script, "#!/bin/sh").expect("write shebang");
        writeln!(script, "{body}").expect("write body");
        script.flush().expect("flush");

        // Make it executable (chmod +x).
        use std::os::unix::fs::PermissionsExt;
        let mut perms = script.as_file().metadata().expect("metadata").permissions();
        perms.set_mode(0o755);
        script
            .as_file()
            .set_permissions(perms)
            .expect("set permissions");

        // Consume the NamedTempFile — this closes the write fd while keeping
        // the file alive on disk via the returned TempPath. Without this step
        // an open write fd would cause ETXTBSY on execve.
        (script.into_temp_path(), dir)
    }

    // ── run_grub_mkconfig_fails_when_binary_not_on_path ───────────────────────

    /// When PATH contains only an empty directory, neither `grub-mkconfig` nor
    /// `grub2-mkconfig` will be found. The function must return
    /// `EspScanFailed`.
    #[test]
    fn run_grub_mkconfig_fails_when_binary_not_on_path() {
        let _guard = lock_path();

        // Point PATH at an empty temp directory so `which` finds nothing.
        let empty_dir = TempDir::new().expect("tempdir");
        std::env::set_var("PATH", empty_dir.path());

        let output_dir = TempDir::new().expect("output tempdir");
        let output_path = output_dir.path().join("grub.cfg");

        let result = run_grub_mkconfig(&output_path);

        // Restore a sane PATH so subsequent tests are not affected.
        std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");

        assert!(
            matches!(result, Err(BootControlError::EspScanFailed { ref reason }) if
                reason.contains("grub-mkconfig not found")),
            "expected EspScanFailed with 'not found' reason, got: {result:?}"
        );
    }

    // ── run_grub_mkconfig_propagates_nonzero_exit ─────────────────────────────

    /// A script that exits 1 and prints a known stderr message must cause the
    /// function to return `EspScanFailed` with that message embedded in the
    /// reason string.
    #[test]
    fn run_grub_mkconfig_propagates_nonzero_exit() {
        let _guard = lock_path();

        let (script, _dir) = make_script("echo 'fatal: disk error' >&2\nexit 1");
        let script_path = script.to_path_buf();

        // The script file name is arbitrary (NamedTempFile uses a random
        // suffix), so we create a symlink named `grub-mkconfig` pointing to it.
        let script_dir = script_path.parent().expect("script parent");
        let link_path = script_dir.join("grub-mkconfig");
        std::fs::hard_link(&script_path, &link_path).unwrap_or_else(|_| {
            std::os::unix::fs::symlink(&script_path, &link_path).expect("symlink")
        });

        std::env::set_var("PATH", script_dir);

        let output_dir = TempDir::new().expect("output tempdir");
        let output_path = output_dir.path().join("grub.cfg");
        let result = run_grub_mkconfig(&output_path);

        // Restore a sane PATH.
        std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");

        match result {
            Err(BootControlError::EspScanFailed { reason }) => {
                assert!(
                    reason.contains("grub-mkconfig failed"),
                    "reason must mention 'grub-mkconfig failed': {reason}"
                );
                assert!(
                    reason.contains("exit 1") || reason.contains("1"),
                    "reason must contain exit code: {reason}"
                );
                assert!(
                    reason.contains("fatal: disk error"),
                    "reason must embed stderr: {reason}"
                );
            }
            other => panic!("expected EspScanFailed, got: {other:?}"),
        }
    }

    // ── run_grub_mkconfig_succeeds_with_zero_exit_stub ───────────────────────

    /// A stub script that simply `exit 0`s, exposed on PATH as `grub-mkconfig`,
    /// must drive `run_grub_mkconfig` to `Ok(())`.
    ///
    /// Previously this test symlinked `/bin/echo` (or `/usr/bin/echo`) and
    /// relied on it ignoring its argv[0]. That works under GNU coreutils but
    /// not under uutils-coreutils (Ubuntu 26.04+), where the multi-call
    /// `echo` binary dispatches on argv[0] and exits non-zero with
    /// "unknown program 'grub-mkconfig'". A dedicated POSIX shell stub is
    /// portable across both.
    #[test]
    fn run_grub_mkconfig_succeeds_with_zero_exit_stub() {
        let _guard = lock_path();

        let (script, _dir) = make_script("exit 0");
        let script_path = script.to_path_buf();
        let script_dir = script_path
            .parent()
            .expect("script parent")
            .to_path_buf();
        let link_path = script_dir.join("grub-mkconfig");
        std::fs::hard_link(&script_path, &link_path).unwrap_or_else(|_| {
            std::os::unix::fs::symlink(&script_path, &link_path).expect("symlink")
        });

        std::env::set_var("PATH", &script_dir);

        let output_dir = TempDir::new().expect("output tempdir");
        let output_path = output_dir.path().join("grub.cfg");
        let result = run_grub_mkconfig(&output_path);

        // Restore a sane PATH.
        std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");

        assert!(
            result.is_ok(),
            "stub exits 0 — run_grub_mkconfig must return Ok(()), got: {result:?}"
        );
    }
}
