//! Trigger `grub-mkconfig` to regenerate `/boot/grub/grub.cfg`.
//!
//! After [`crate::grub_manager::set_grub_value`] atomically writes
//! `/etc/default/grub`, the changes are on-disk but not yet active at boot.
//! GRUB reads `/boot/grub/grub.cfg`, which is only regenerated by an explicit
//! `grub-mkconfig -o /boot/grub/grub.cfg` (Debian/Ubuntu/Arch) or
//! `grub2-mkconfig -o /boot/grub/grub.cfg` (RHEL/Fedora/openSUSE) invocation.
//!
//! This module locates whichever variant is present on `$PATH` and runs it.
//!
//! # Error mapping
//!
//! All errors are surfaced as [`BootControlError::EspScanFailed`] with a
//! human-readable reason string. Clients catch
//! `org.bootcontrol.Error.EspScanFailed` over D-Bus.

use std::path::Path;

use bootcontrol_core::error::BootControlError;
use tracing::info;
use which::which;

/// Locate and run `grub-mkconfig` (or `grub2-mkconfig`) to regenerate the
/// GRUB configuration file.
///
/// The function probes `$PATH` for `grub-mkconfig` first and falls back to
/// `grub2-mkconfig` so that both Debian/Ubuntu/Arch and RHEL/Fedora families
/// are supported transparently.
///
/// # Arguments
///
/// * `output_path` — Destination path for the generated `grub.cfg`.
///   Production code passes `/boot/grub/grub.cfg`; tests inject a temporary
///   path to avoid touching the live system.
///
/// # Errors
///
/// Returns [`BootControlError::EspScanFailed`] when:
/// - Neither `grub-mkconfig` nor `grub2-mkconfig` is found on `$PATH`.
/// - The command exits with a non-zero status (the reason includes stderr).
/// - Any I/O error occurs while spawning the child process.
///
/// # Examples
///
/// ```no_run
/// use std::path::Path;
/// use bootcontrold::grub_rebuild::run_grub_mkconfig;
///
/// // Production usage — requires root and a real GRUB installation.
/// run_grub_mkconfig(Path::new("/boot/grub/grub.cfg")).unwrap();
/// ```
pub fn run_grub_mkconfig(output_path: &Path) -> Result<(), BootControlError> {
    // ── Step 1: Locate the binary ─────────────────────────────────────────────
    let binary = which("grub-mkconfig")
        .or_else(|_| which("grub2-mkconfig"))
        .map_err(|_| BootControlError::EspScanFailed {
            reason: "grub-mkconfig not found; install grub-common or grub2-common".to_string(),
        })?;

    info!(binary = ?binary, output_path = ?output_path, "running grub-mkconfig");

    // ── Step 2: Run the command, capturing stdout + stderr ────────────────────
    let output = std::process::Command::new(&binary)
        .arg("-o")
        .arg(output_path)
        .output()
        .map_err(|e| BootControlError::EspScanFailed {
            reason: format!("failed to spawn {}: {e}", binary.display()),
        })?;

    // ── Step 3: Check exit status ─────────────────────────────────────────────
    if !output.status.success() {
        let code = output
            .status
            .code()
            .map(|c| c.to_string())
            .unwrap_or_else(|| "signal".to_string());
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        return Err(BootControlError::EspScanFailed {
            reason: format!("grub-mkconfig failed (exit {code}): {stderr}"),
        });
    }

    info!(output_path = ?output_path, "grub-mkconfig completed successfully");
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::Mutex;
    use tempfile::{NamedTempFile, TempDir};

    // ── PATH serialization lock ───────────────────────────────────────────────
    //
    // Tests that manipulate the process-wide PATH environment variable MUST
    // hold this lock for the duration of the manipulation. Because Rust tests
    // run in parallel by default and PATH is a global resource, concurrent
    // manipulation would cause non-deterministic failures.
    //
    // Usage pattern:
    //   let _guard = PATH_LOCK.lock().expect("PATH lock poisoned");
    //   std::env::set_var("PATH", ...);
    //   ... test body ...
    //   std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");
    //   // _guard dropped here → next test can proceed
    pub(crate) static PATH_LOCK: Mutex<()> = Mutex::new(());

    // ── Helper: create a temporary shell script ───────────────────────────────

    /// Write a shell script to a NamedTempFile, set it executable, and return
    /// both the file and the directory it lives in (keeping the TempDir alive
    /// so the directory is not deleted while the file is in use).
    fn make_script(body: &str) -> (NamedTempFile, TempDir) {
        let dir = TempDir::new().expect("tempdir");
        let mut script = NamedTempFile::new_in(dir.path()).expect("script tempfile");
        writeln!(script, "#!/bin/sh").expect("write shebang");
        writeln!(script, "{body}").expect("write body");
        script.flush().expect("flush");

        // Make it executable (chmod +x).
        use std::os::unix::fs::PermissionsExt;
        let mut perms = script.as_file().metadata().expect("metadata").permissions();
        perms.set_mode(0o755);
        script
            .as_file()
            .set_permissions(perms)
            .expect("set permissions");

        (script, dir)
    }

    // ── run_grub_mkconfig_fails_when_binary_not_on_path ───────────────────────

    /// When PATH contains only an empty directory, neither `grub-mkconfig` nor
    /// `grub2-mkconfig` will be found. The function must return
    /// `EspScanFailed`.
    #[test]
    fn run_grub_mkconfig_fails_when_binary_not_on_path() {
        let _guard = PATH_LOCK.lock().expect("PATH lock poisoned");

        // Point PATH at an empty temp directory so `which` finds nothing.
        let empty_dir = TempDir::new().expect("tempdir");
        std::env::set_var("PATH", empty_dir.path());

        let output_dir = TempDir::new().expect("output tempdir");
        let output_path = output_dir.path().join("grub.cfg");

        let result = run_grub_mkconfig(&output_path);

        // Restore a sane PATH so subsequent tests are not affected.
        std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");

        assert!(
            matches!(result, Err(BootControlError::EspScanFailed { ref reason }) if
                reason.contains("grub-mkconfig not found")),
            "expected EspScanFailed with 'not found' reason, got: {result:?}"
        );
    }

    // ── run_grub_mkconfig_propagates_nonzero_exit ─────────────────────────────

    /// A script that exits 1 and prints a known stderr message must cause the
    /// function to return `EspScanFailed` with that message embedded in the
    /// reason string.
    #[test]
    fn run_grub_mkconfig_propagates_nonzero_exit() {
        let _guard = PATH_LOCK.lock().expect("PATH lock poisoned");

        let (script, _dir) = make_script("echo 'fatal: disk error' >&2\nexit 1");
        let script_path = script.path().to_path_buf();

        // The script file name is arbitrary (NamedTempFile uses a random
        // suffix), so we create a symlink named `grub-mkconfig` pointing to it.
        let script_dir = script_path.parent().expect("script parent");
        let link_path = script_dir.join("grub-mkconfig");
        std::fs::hard_link(&script_path, &link_path).unwrap_or_else(|_| {
            std::os::unix::fs::symlink(&script_path, &link_path).expect("symlink")
        });

        std::env::set_var("PATH", script_dir);

        let output_dir = TempDir::new().expect("output tempdir");
        let output_path = output_dir.path().join("grub.cfg");
        let result = run_grub_mkconfig(&output_path);

        // Restore a sane PATH.
        std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");

        match result {
            Err(BootControlError::EspScanFailed { reason }) => {
                assert!(
                    reason.contains("grub-mkconfig failed"),
                    "reason must mention 'grub-mkconfig failed': {reason}"
                );
                assert!(
                    reason.contains("exit 1") || reason.contains("1"),
                    "reason must contain exit code: {reason}"
                );
                assert!(
                    reason.contains("fatal: disk error"),
                    "reason must embed stderr: {reason}"
                );
            }
            other => panic!("expected EspScanFailed, got: {other:?}"),
        }
    }

    // ── run_grub_mkconfig_succeeds_with_real_echo_binary ─────────────────────

    /// `/bin/echo` (or `/usr/bin/echo`) is available on every POSIX system and
    /// exits 0. When we expose it as `grub-mkconfig` on PATH via a symlink,
    /// the function must return `Ok(())`.
    ///
    /// The test locates `echo` by searching a set of well-known fixed paths so
    /// it is not confused by PATH manipulation in sibling tests.
    #[test]
    fn run_grub_mkconfig_succeeds_with_real_echo_binary() {
        let _guard = PATH_LOCK.lock().expect("PATH lock poisoned");

        // Locate `echo` at a well-known fixed path — do NOT use `which` here
        // because sibling tests manipulate the process-wide PATH and `which`
        // respects that.
        let echo_bin = ["/bin/echo", "/usr/bin/echo"]
            .iter()
            .find(|p| std::path::Path::new(p).is_file())
            .expect("echo must exist at /bin/echo or /usr/bin/echo on the test host");

        // Create a symlink named `grub-mkconfig` → real `echo` in a temp dir.
        let link_dir = TempDir::new().expect("link tempdir");
        let link_path = link_dir.path().join("grub-mkconfig");
        std::os::unix::fs::symlink(echo_bin, &link_path).expect("symlink echo");

        std::env::set_var("PATH", link_dir.path());

        let output_dir = TempDir::new().expect("output tempdir");
        let output_path = output_dir.path().join("grub.cfg");
        let result = run_grub_mkconfig(&output_path);

        // Restore a sane PATH.
        std::env::set_var("PATH", "/usr/bin:/bin:/usr/sbin:/sbin");

        assert!(
            result.is_ok(),
            "echo exits 0 — run_grub_mkconfig must return Ok(()), got: {result:?}"
        );
    }
}
