//! Parser for the *generated* `grub.cfg` menu structure.
//!
//! This module is the read-only half of GRUB menu-entry management
//! (A1 chunk 1, spec v1 §3.2 + v2 §10.2): it extracts the list of
//! `menuentry` / `submenu` items that GRUB would show at boot, so the
//! frontends can display them and `GRUB_DEFAULT` can be set by index
//! path or id.
//!
//! It never mutates anything — `grub.cfg` is a generated artifact owned
//! by `grub-mkconfig`. Mutation happens upstream (`/etc/default/grub`,
//! `/etc/grub.d/`) in later chunks.
//!
//! Like every parser in this crate it is a pure function over `&str`
//! (see `crates/core/CLAUDE.md`): no I/O, no `unwrap`/`expect`, no
//! panics on any input.

use crate::error::BootControlError;

/// One boot menu item parsed from a generated `grub.cfg`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GrubMenuEntry {
    /// Menu title as GRUB displays it — dequoted and unescaped.
    pub title: String,
    /// Stable identifier from `$menuentry_id_option '<id>'`, if present.
    pub id: Option<String>,
    /// `GRUB_DEFAULT`-compatible numeric index path.
    ///
    /// Top-level items get `"0"`, `"1"`, … in file order (submenus
    /// occupy an index just like plain entries). Children of a submenu
    /// get `"<parent path>><child index>"`, e.g. `"1>0"`; nesting is
    /// unbounded, e.g. `"0>1>0"`.
    pub path: String,
    /// Nesting depth: `0` = top level, `1` = inside one submenu, …
    pub depth: usize,
    /// `true` when this item is a `submenu` container (its children
    /// follow in the returned list), `false` for a bootable `menuentry`.
    pub is_submenu: bool,
}

/// Parse the menu structure out of a generated `grub.cfg`.
///
/// Returns every `menuentry` and `submenu` in file order. Content
/// outside menu blocks (`set` commands, functions, `if` blocks,
/// comments) is ignored. Lines inside a `menuentry` body are ignored.
///
/// # Errors
///
/// Returns [`BootControlError::MalformedValue`] (with `key ==
/// "grub.cfg"`) when a `menuentry`/`submenu` line has no opening `{`
/// on the same line, when a title/id quote is unterminated, or when
/// the file ends before every opened block is closed.
///
/// # Examples
///
/// ```
/// use bootcontrol_core::grub_cfg::parse_menu_entries;
///
/// let cfg = r#"
/// menuentry 'Ubuntu' --class ubuntu $menuentry_id_option 'gnulinux-simple-abc' {
///     linux /vmlinuz root=UUID=abc ro quiet
/// }
/// "#;
/// let entries = parse_menu_entries(cfg).expect("valid cfg parses");
/// assert_eq!(entries.len(), 1);
/// assert_eq!(entries[0].title, "Ubuntu");
/// assert_eq!(entries[0].id.as_deref(), Some("gnulinux-simple-abc"));
/// assert_eq!(entries[0].path, "0");
/// assert!(!entries[0].is_submenu);
/// ```
pub fn parse_menu_entries(_cfg: &str) -> Result<Vec<GrubMenuEntry>, BootControlError> {
    todo!("A1 chunk 1: implement per the work-order and the tests below")
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests — THE CONTRACT. Do not modify tests; make them pass.
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Realistic Ubuntu-style fixture: os-prober Windows entry, one
    /// submenu with two children, function + if noise around them.
    const UBUNTU_FIXTURE: &str = r#"#
# DO NOT EDIT THIS FILE
#
function load_video {
  insmod all_video
}
set default="0"
if [ x"${feature_menuentry_id}" = xy ]; then
  menuentry_id_option="--id"
fi
menuentry 'Ubuntu' --class ubuntu --class gnu-linux --class os $menuentry_id_option 'gnulinux-simple-2f1a' {
        recordfail
        load_video
        linux   /boot/vmlinuz-6.8.0 root=UUID=2f1a ro quiet splash
        initrd  /boot/initrd.img-6.8.0
}
submenu 'Advanced options for Ubuntu' $menuentry_id_option 'gnulinux-advanced-2f1a' {
        menuentry 'Ubuntu, with Linux 6.8.0' --class ubuntu $menuentry_id_option 'gnulinux-6.8.0-advanced-2f1a' {
                linux   /boot/vmlinuz-6.8.0 root=UUID=2f1a ro quiet splash
                initrd  /boot/initrd.img-6.8.0
        }
        menuentry 'Ubuntu, with Linux 6.8.0 (recovery mode)' --class ubuntu $menuentry_id_option 'gnulinux-6.8.0-recovery-2f1a' {
                linux   /boot/vmlinuz-6.8.0 root=UUID=2f1a ro recovery nomodeset
                initrd  /boot/initrd.img-6.8.0
        }
}
menuentry "Windows Boot Manager (on /dev/nvme0n1p1)" --class windows --class os $menuentry_id_option 'osprober-efi-9C2A-1111' {
        insmod part_gpt
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
"#;

    fn parse(cfg: &str) -> Vec<GrubMenuEntry> {
        parse_menu_entries(cfg).expect("fixture must parse cleanly")
    }

    fn malformed(cfg: &str) -> BootControlError {
        match parse_menu_entries(cfg) {
            Err(e) => e,
            Ok(v) => panic!("expected MalformedValue, got Ok({v:?})"),
        }
    }

    // ── happy path ──────────────────────────────────────────────────────────

    #[test]
    fn empty_input_returns_empty_vec() {
        assert_eq!(parse(""), Vec::new());
    }

    #[test]
    fn file_without_entries_returns_empty_vec() {
        let cfg = "set default=\"0\"\nset timeout=5\nfunction f {\n  true\n}\n";
        assert_eq!(parse(cfg), Vec::new());
    }

    #[test]
    fn single_entry_parses_title_id_path_depth() {
        let cfg = "menuentry 'Ubuntu' --class ubuntu $menuentry_id_option 'gnulinux-simple-2f1a' {\n\tlinux /vmlinuz\n}\n";
        let e = &parse(cfg)[0];
        assert_eq!(e.title, "Ubuntu");
        assert_eq!(e.id.as_deref(), Some("gnulinux-simple-2f1a"));
        assert_eq!(e.path, "0");
        assert_eq!(e.depth, 0);
        assert!(!e.is_submenu);
    }

    #[test]
    fn double_quoted_title_is_dequoted() {
        let cfg = "menuentry \"Windows Boot Manager\" --class windows {\n\tchainloader /x\n}\n";
        let e = &parse(cfg)[0];
        assert_eq!(e.title, "Windows Boot Manager");
    }

    #[test]
    fn entry_without_id_option_has_none_id() {
        let cfg = "menuentry 'Plain' {\n\ttrue\n}\n";
        assert_eq!(parse(cfg)[0].id, None);
    }

    #[test]
    fn sequential_top_level_entries_get_sequential_paths() {
        let cfg = "menuentry 'A' {\n}\nmenuentry 'B' {\n}\n";
        let v = parse(cfg);
        assert_eq!(v[0].path, "0");
        assert_eq!(v[1].path, "1");
    }

    #[test]
    fn apostrophe_escape_in_single_quoted_title() {
        // grub-mkconfig writes an apostrophe inside a single-quoted title
        // as: close quote, escaped quote, reopen quote.
        let cfg = "menuentry 'Tom'\\''s Linux' {\n\ttrue\n}\n";
        assert_eq!(parse(cfg)[0].title, "Tom's Linux");
    }

    #[test]
    fn body_lines_never_produce_entries() {
        let cfg = "menuentry 'A' {\n\techo 'menuentry fake'\n\tlinux /vmlinuz\n}\n";
        assert_eq!(parse(cfg).len(), 1);
    }

    #[test]
    fn commented_out_entries_are_ignored() {
        let cfg = "# menuentry 'Old' {\nmenuentry 'Real' {\n}\n";
        let v = parse(cfg);
        assert_eq!(v.len(), 1);
        assert_eq!(v[0].title, "Real");
    }

    #[test]
    fn crlf_input_parses() {
        let cfg = "menuentry 'A' {\r\n\tlinux /x\r\n}\r\n";
        assert_eq!(parse(cfg)[0].title, "A");
    }

    // ── submenus ────────────────────────────────────────────────────────────

    #[test]
    fn submenu_is_listed_and_children_get_arrow_paths() {
        let v = parse(UBUNTU_FIXTURE);
        let titles: Vec<&str> = v.iter().map(|e| e.title.as_str()).collect();
        assert_eq!(
            titles,
            vec![
                "Ubuntu",
                "Advanced options for Ubuntu",
                "Ubuntu, with Linux 6.8.0",
                "Ubuntu, with Linux 6.8.0 (recovery mode)",
                "Windows Boot Manager (on /dev/nvme0n1p1)",
            ]
        );

        let adv = &v[1];
        assert!(adv.is_submenu);
        assert_eq!(adv.path, "1");
        assert_eq!(adv.depth, 0);
        assert_eq!(adv.id.as_deref(), Some("gnulinux-advanced-2f1a"));

        assert_eq!(v[2].path, "1>0");
        assert_eq!(v[2].depth, 1);
        assert!(!v[2].is_submenu);
        assert_eq!(v[3].path, "1>1");

        // Submenu occupies index 1, so Windows is index 2 — not 4.
        assert_eq!(v[4].path, "2");
        assert_eq!(v[4].depth, 0);
        assert_eq!(v[4].id.as_deref(), Some("osprober-efi-9C2A-1111"));
    }

    #[test]
    fn nested_submenus_extend_the_path() {
        let cfg = "submenu 'Outer' {\n\tsubmenu 'Inner' {\n\t\tmenuentry 'Leaf' {\n\t\t}\n\t}\n}\n";
        let v = parse(cfg);
        assert_eq!(v[0].path, "0");
        assert_eq!(v[1].path, "0>0");
        assert!(v[1].is_submenu);
        assert_eq!(v[2].path, "0>0>0");
        assert_eq!(v[2].depth, 2);
        assert_eq!(v[2].title, "Leaf");
    }

    // ── errors ──────────────────────────────────────────────────────────────

    #[test]
    fn unterminated_block_is_malformed() {
        let cfg = "menuentry 'A' {\n\tlinux /x\n";
        let e = malformed(cfg);
        assert!(
            matches!(e, BootControlError::MalformedValue { ref key, .. } if key == "grub.cfg"),
            "got: {e:?}"
        );
    }

    #[test]
    fn missing_opening_brace_is_malformed() {
        let cfg = "menuentry 'A'\n{\n}\n";
        let e = malformed(cfg);
        assert!(
            matches!(e, BootControlError::MalformedValue { .. }),
            "got: {e:?}"
        );
    }

    #[test]
    fn unterminated_title_quote_is_malformed() {
        let cfg = "menuentry 'Never closed {\n}\n";
        let e = malformed(cfg);
        assert!(
            matches!(e, BootControlError::MalformedValue { .. }),
            "got: {e:?}"
        );
    }
}
